name: Java CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build and Run All Tests
      run: |
        cd teamproject
        mvn clean verify

    - name: Run Checkstyle
      run: |
        cd teamproject
        mvn checkstyle:checkstyle
    - name: Upload Checkstyle Report
      uses: actions/upload-artifact@v3
      with:
        name: checkstyle-report
        path: teamproject/target/site/checkstyle.html

    - name: Run PMD Static Analysis
      run: |
        cd teamproject
        mvn pmd:check || true
    - name: Upload PMD Report
      uses: actions/upload-artifact@v3
      with:
        name: pmd-report
        path: teamproject/target/site/pmd.html

    - name: Run JaCoCo Coverage
      run: |
        cd teamproject
        mvn jacoco:report
    - name: Upload JaCoCo Report
      uses: actions/upload-artifact@v3
      with:
        name: jacoco-report
        path: teamproject/target/site/jacoco/index.html

    - name: Generate Coverage Summary
      uses: danielpalme/ReportGenerator-GitHub-Action@5.2.0
      with:
        reports: finalproject/teamproject/target/site/jacoco/jacoco.xml
        reporttypes: HtmlInline;Cobertura;TextSummary
        sourcedirs: finalproject/teamproject/src/main/java
        title: JaCoCo Code Coverage Report
    - name: Save Coverage Summary to Summary.txt
      run: |
        cd finalproject/teamproject/target/site/jacoco
        echo "Generating coverage summary..."
        danielpalme/ReportGenerator-GitHub-Action@5.2.0 | Out-File Summary.txt -Encoding utf8
    - name: Upload Coverage Summary
      uses: actions/upload-artifact@v3
      with:
        name: coverage-summary
        path: finalproject/teamproject/target/site/jacoco/Summary.txt
