name: Java CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build and Run All Tests
      run: mvn clean verify

    - name: Run Checkstyle
      run: mvn checkstyle:checkstyle
    - name: Upload Checkstyle Report
      uses: actions/upload-artifact@v2
      with:
        name: checkstyle-report
        path: target/site/checkstyle.html

    - name: Run PMD Static Analysis
      run: mvn pmd:check
    - name: Upload PMD Report
      uses: actions/upload-artifact@v2
      with:
        name: pmd-report
        path: target/site/pmd.html

    - name: Run JaCoCo Coverage
      run: mvn jacoco:report
    - name: Upload JaCoCo Report
      uses: actions/upload-artifact@v2
      with:
        name: jacoco-report
        path: target/site/jacoco/index.html

    - name: Generate Coverage Summary
      uses: danielpalme/ReportGenerator-GitHub-Action@5.2.0
      with:
        reports: target/site/jacoco/jacoco.xml
        reporttypes: HtmlInline;Cobertura;TextSummary
        sourcedirs: src/main/java
        title: JaCoCo Code Coverage Report
    - name: Upload Coverage Summary
      run: cat target/site/jacoco/Summary.txt || echo "No summary available"
