name: Java CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: teamproject
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build and Run All Tests
      run: mvn clean verify

    - name: Run Checkstyle
      run: mvn checkstyle:checkstyle

    - name: Run PMD Static Analysis
      run: mvn pmd:check || true

    - name: Run JaCoCo Coverage
      run: mvn jacoco:report
