name: Java CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: teamproject
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build and Run All Tests
      run: mvn clean verify

    - name: Run Checkstyle
      run: mvn checkstyle:checkstyle
    - name: Upload Checkstyle Report
      uses: actions/upload-artifact@v3
      with:
        name: checkstyle-report
        path: teamproject/target/site/checkstyle.html

    - name: Run PMD Static Analysis
      run: mvn pmd:check || true
    - name: Upload PMD Report
      uses: actions/upload-artifact@v3
      with:
        name: pmd-report
        path: teamproject/target/site/pmd.html

    - name: Run JaCoCo Coverage
      run: mvn jacoco:report
    - name: Upload JaCoCo Report
      uses: actions/upload-artifact@v3
      with:
        name: jacoco-report
        path: teamproject/target/site/jacoco/index.html
